# -*- coding: utf-8 -*-
"""heart_deployement.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGOcCtdzfw3w3tlMmPx1PNP5-q6YtSL9
"""

import streamlit as st
import joblib
import pandas as pd

model =joblib.load("dtc_model.pkl")

st.title("Heart attack model💓💘")

Age = st.number_input("Age")
Gender= st.number_input("Gender")
Heart_Rate= st.number_input("Heart_Rate")
Systolic_Blood_Pressure= st.number_input("Systolic_Blood_Pressure")
Diastolic_Blood_Pressure= st.number_input("Diastolic_Blood_Pressure")
Blood_Sugar= st.number_input("Blood_Sugar")
CK-MB= st.number_input("CK-MB")
Troponin= st.number_input("Troponin")


input_data = pd.DataFrame([[
 Age,
 Gender,
 Heart_Rate,
 Systolic_Blood_Pressure,
 Diastolic_Blood_Pressure,
 Blood_Sugar,
 CK-MB,
 Troponin
]], columns=model.feature_names_in_)

if st.button("Result"):
  RESULT=model.predict(input_data)
  if RESULT =="negative":
    st.write("NEGETIVE")
  else:
    st.write("POSITIVE")